a= ['=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 1)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 2)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 3)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 4)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 5)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 6)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 7)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 8)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 9)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 10)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 11)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 12)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 13)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 14)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 15)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 16)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 17)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 18)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 19)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 20)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 21)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 22)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 23)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 24)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 25)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 26)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 27)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 28)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 29)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 30)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 31)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 32)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 33)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 34)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 35)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 36)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 37)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 38)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 39)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 40)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 41)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 42)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 43)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 44)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 45)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 46)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 47)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 48)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 49)',
'=IMPORTHTML("https://www.zyxware.com/articles/4344/list-of-fortune-500-companies-and-their-websites","table", 50)'
]


for aa in a:
    print(aa)
    for aa in range(10):
        print()